#!/usr/bin/env bash
#type of network a computer local is connected to
3

#type of network could connect an office in one building
#to another office :in a building a few streets away
3
#network you use when you browse www.google.com
#from your smartphone
2
