#!/usr/bin/env bash
#creating a nginx user
pkill -f apache2
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo chmod 204 /etc/nginx/nginx.conf
sed -i "1iuser nginx;" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
